In [71]:
import numpy as np

DATASET_SIZE = 20

In [74]:
# np.random.seed(42)
# X = np.random.randint(DATASET_SIZE,size=DATASET_SIZE)

X = list(range(DATASET_SIZE))

np.random.seed(42)
y = np.random.randint(2, size=DATASET_SIZE)
y

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0])

In [102]:
from sklearn.model_selection import StratifiedShuffleSplit
stratidied_splitter1 = StratifiedShuffleSplit(n_splits=3, test_size=0.2, random_state=42)

for train_index , test_index in stratidied_splitter1.split(X, y):
    print('train_index')
    print(train_index)
    print('test_index')
    print(test_index)
    print('\n\n')


train_index
[19  5  1 11 17  2  0 14  6  3 10 16 15  7 18 12]
test_index
[13  9  8  4]



train_index
[17  1  5 18 16  9 12 10  7 19  6  0  2 13  4 11]
test_index
[ 8  3 14 15]



train_index
[ 3 19 10  8  0 11 18 15 14  6  5  1  9 17 13 12]
test_index
[16  7  2  4]





In [95]:
from sklearn.model_selection import StratifiedKFold
stratidied_splitter2 = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

In [99]:
for train_index , test_index in stratidied_splitter2.split(X, y):
    print('train_index')
    print(train_index)
    print('test_index')
    print(test_index)
    print('\n\n')


train_index
[ 0  2  4  5  6  9 10 12 13 16 17 18 19]
test_index
[ 1  3  7  8 11 14 15]



train_index
[ 0  1  2  3  5  7  8 10 11 13 14 15 17]
test_index
[ 4  6  9 12 16 18 19]



train_index
[ 1  3  4  6  7  8  9 11 12 14 15 16 18 19]
test_index
[ 0  2  5 10 13 17]





In [90]:
from sklearn.model_selection import StratifiedGroupKFold
stratidied_splitter3 = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

In [92]:
for train_index , test_index in stratidied_splitter3.split(X, y):
    print('train_index')
    print(train_index)
    print('test_index')
    print(test_index)
    print('\n\n')

train_index
[ 0  2  4  5  6  9 10 12 13 16 17 18 19]
test_index
[ 1  3  7  8 11 14 15]



train_index
[ 0  1  2  3  5  7  8 10 11 13 14 15 17]
test_index
[ 4  6  9 12 16 18 19]



train_index
[ 1  3  4  6  7  8  9 11 12 14 15 16 18 19]
test_index
[ 0  2  5 10 13 17]





In [82]:
from sklearn.model_selection import RepeatedStratifiedKFold
stratidied_splitter4 = RepeatedStratifiedKFold(n_splits=3,n_repeats=4, random_state=42)

In [83]:
for train_index , test_index in stratidied_splitter4.split(X, y):
    print('train_index')
    print(train_index)
    print('test_index')
    print(test_index)
    print('\n\n')

train_index
[ 0  2  4  5  6  9 10 12 13 16 17 18 19]
test_index
[ 1  3  7  8 11 14 15]



train_index
[ 0  1  2  3  5  7  8 10 11 13 14 15 17]
test_index
[ 4  6  9 12 16 18 19]



train_index
[ 1  3  4  6  7  8  9 11 12 14 15 16 18 19]
test_index
[ 0  2  5 10 13 17]



train_index
[ 0  2  3  5  6  7  9 10 11 14 15 16 17]
test_index
[ 1  4  8 12 13 18 19]



train_index
[ 0  1  4  5  7  8 10 12 13 15 16 18 19]
test_index
[ 2  3  6  9 11 14 17]



train_index
[ 1  2  3  4  6  8  9 11 12 13 14 17 18 19]
test_index
[ 0  5  7 10 15 16]



train_index
[ 0  1  3  5  6  7  9 10 11 13 15 16 18]
test_index
[ 2  4  8 12 14 17 19]



train_index
[ 0  1  2  4  6  8 10 12 14 15 16 17 19]
test_index
[ 3  5  7  9 11 13 18]



train_index
[ 2  3  4  5  7  8  9 11 12 13 14 17 18 19]
test_index
[ 0  1  6 10 15 16]



train_index
[ 0  1  2  5  6  7  8  9 10 15 16 18 19]
test_index
[ 3  4 11 12 13 14 17]



train_index
[ 0  1  2  3  4 10 11 12 13 14 15 17 18]
test_index
[ 5  6  7  8  9 16 19]



train_inde