# Create small dataset

In [21]:
import numpy as np

DATASET_SIZE = 20
RANDOM_STATE = 42

X = list(range(DATASET_SIZE))
np.random.seed(42)
y = np.random.randint(2, size=DATASET_SIZE)

# Spliting techniques

The simplest technique to split a data set since we have shuffle it, firstly.

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, shuffle=True, test_size=0.2, random_state=RANDOM_STATE)

print('X_train:',X_train)
print('X_test:',X_test)
print('y_train:',y_train)
print('y_test:',y_test)


X_train: [8, 5, 11, 3, 18, 16, 13, 2, 9, 19, 4, 12, 7, 10, 14, 6]
X_test: [0, 17, 15, 1]
y_train: [0 1 0 0 1 1 0 0 1 0 0 0 0 0 1 0]
y_test: [0 1 0 1]


# Cross validation using Stratified spliting technique

## klearn.model_selection.StratifiedShuffleSplit

if you want to take n times shuffled and with the same analogy in terms of target's categories thry the follow one:

In [16]:
from sklearn.model_selection import StratifiedShuffleSplit
stratidied_splitter1 = StratifiedShuffleSplit(n_splits=3, test_size=0.2, random_state=RANDOM_STATE)

for train_index , test_index in stratidied_splitter1.split(X, y):
    print('train_index')
    print(train_index)
    print('test_index')
    print(test_index)
    print('\n\n')


train_index
[19  5  1 11 17  2  0 14  6  3 10 16 15  7 18 12]
test_index
[13  9  8  4]



train_index
[17  1  5 18 16  9 12 10  7 19  6  0  2 13  4 11]
test_index
[ 8  3 14 15]



train_index
[ 3 19 10  8  0 11 18 15 14  6  5  1  9 17 13 12]
test_index
[16  7  2  4]





In [17]:
from sklearn.model_selection import StratifiedKFold
stratidied_splitter2 = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_STATE)

for train_index , test_index in stratidied_splitter2.split(X, y):
    print('train_index')
    print(train_index)
    print('test_index')
    print(test_index)
    print('\n\n')

train_index
[ 0  2  4  5  6  9 10 12 13 16 17 18 19]
test_index
[ 1  3  7  8 11 14 15]



train_index
[ 0  1  2  3  5  7  8 10 11 13 14 15 17]
test_index
[ 4  6  9 12 16 18 19]



train_index
[ 1  3  4  6  7  8  9 11 12 14 15 16 18 19]
test_index
[ 0  2  5 10 13 17]





In [18]:
from sklearn.model_selection import StratifiedGroupKFold
stratidied_splitter3 = StratifiedKFold(n_splits=3, shuffle=True, random_state=RANDOM_STATE)

for train_index , test_index in stratidied_splitter3.split(X, y):
    print('train_index')
    print(train_index)
    print('test_index')
    print(test_index)
    print('\n\n')

train_index
[ 0  2  4  5  6  9 10 12 13 16 17 18 19]
test_index
[ 1  3  7  8 11 14 15]



train_index
[ 0  1  2  3  5  7  8 10 11 13 14 15 17]
test_index
[ 4  6  9 12 16 18 19]



train_index
[ 1  3  4  6  7  8  9 11 12 14 15 16 18 19]
test_index
[ 0  2  5 10 13 17]





In [19]:
from sklearn.model_selection import RepeatedStratifiedKFold
stratidied_splitter4 = RepeatedStratifiedKFold(n_splits=3,n_repeats=4, random_state=RANDOM_STATE)

for train_index , test_index in stratidied_splitter4.split(X, y):
    print('train_index')
    print(train_index)
    print('test_index')
    print(test_index)
    print('\n\n')

train_index
[ 0  2  4  5  6  9 10 12 13 16 17 18 19]
test_index
[ 1  3  7  8 11 14 15]



train_index
[ 0  1  2  3  5  7  8 10 11 13 14 15 17]
test_index
[ 4  6  9 12 16 18 19]



train_index
[ 1  3  4  6  7  8  9 11 12 14 15 16 18 19]
test_index
[ 0  2  5 10 13 17]



train_index
[ 0  2  3  5  6  7  9 10 11 14 15 16 17]
test_index
[ 1  4  8 12 13 18 19]



train_index
[ 0  1  4  5  7  8 10 12 13 15 16 18 19]
test_index
[ 2  3  6  9 11 14 17]



train_index
[ 1  2  3  4  6  8  9 11 12 13 14 17 18 19]
test_index
[ 0  5  7 10 15 16]



train_index
[ 0  1  3  5  6  7  9 10 11 13 15 16 18]
test_index
[ 2  4  8 12 14 17 19]



train_index
[ 0  1  2  4  6  8 10 12 14 15 16 17 19]
test_index
[ 3  5  7  9 11 13 18]



train_index
[ 2  3  4  5  7  8  9 11 12 13 14 17 18 19]
test_index
[ 0  1  6 10 15 16]



train_index
[ 0  1  2  5  6  7  8  9 10 15 16 18 19]
test_index
[ 3  4 11 12 13 14 17]



train_index
[ 0  1  2  3  4 10 11 12 13 14 15 17 18]
test_index
[ 5  6  7  8  9 16 19]



train_inde